services:
  back-end:
    build:
      context: ChatBackend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://container_postgres:5432/chat_app
      DB_USERNAME: postgres
      DB_PASSWORD: ujLG5xV4
    depends_on:
      - container_postgres
    networks:
      - my_network

  front-end:
    build:
      context: chat_frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - my_network
    depends_on:
      - back-end

  container_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ujLG5xV4
      POSTGRES_DB: chat_app 
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
